spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chemreg
    username: chemreg_user
    password: chemreg_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs